<?php
require_once '../classTag/Tag.php';

class Link extends Tag
{
	const ACTIVE_CLASS = 'active';
	
	public function __construct()
	{
		
		parent::__construct('a');
		$this->setAttr('href', '');
	}
	
	public function open()
	{
		$this->activateSelf();

		return parent::open(); // TODO: Change the autogenerated stub
	}

	private function activateSelf()
	{
	
		if ($this->getAttr('href') === $_SERVER['REQUEST_URI']) {
			$this->addClass(self::ACTIVE_CLASS);
		}
	}
	
}